### ISSUE TITLE
Allow managing strings-batchfcm.xml generation in config.xml

### ISSUE THREAD

**Issue by amirhmoradi** [BatchLabs/cordova-plugin#8]
Hi,
Please allow enabling/disabling the "strings-batchfcm.xml" file generation based on <preference> tags in config.xml as this would provide more compatibility with other firebase oriented plugins.

Currently, your cordova plugin is only compatible with cordova-plugin-firebase , and causes compilation errors (duplicate xml entries) if used with any other firebase oriented plugins.

Thanks.

**Comment by amirhmoradi** [comment]
you can use [https://cordova.apache.org/docs/en/latest/guide/appdev/hooks/index.html](cordova hooks)
Here is an example of a plugin working with xml files [https://github.com/fairmanager-cordova/plugin-localization-strings.git](fairmanager-cordova-plugin-localization-strings)

**Comment by abarisain** [comment]
Thanks, this is what we already use.

I was wondering is there was some standard way to add flags to plugins when adding them to your cordova project. I'm not finding anything like that so looks like I'm gonna have to parse cordova's file myself and look for a predefined config tag

**Comment by amirhmoradi** [comment]
Here is an example of adding variables when installing a plugin [firebase crashlytics] (https://github.com/ReallySmallSoftware/cordova-plugin-firebase-crashlytics) :
`cordova plugin add cordova-plugin-firebase-crashlytics --variable ANDROID_FIREBASE_CORE_VERSION=16.0.0 --save`

**Comment by abarisain** [comment]
Thanks a lot, it's perfect for that use-case! I'll update this issue when implemented
