### ISSUE TITLE
Build Failed

### ISSUE THREAD

**Issue by Pezhvak** [BatchLabs/cordova-plugin#9]
hi, 
i have cordova-firebase installed on my ionic project and when i try to build i get the following error

FAILURE: Build failed with an exception.
[cordova]
[cordova]  * What went wrong:
[cordova]  Could not resolve all files for configuration ':app:debugCompileClasspath'.
[cordova]  > Could not find com.google.android.gms:play-services-ads-identifier:11.0.4.
[cordova]    Searched in the following locations:
[cordova]        file:/Users/pezhvak/Library/Android/sdk/extras/m2repository/com/google/android/gms/play-services-ads-identifier/11.0.4/play-services-ads-identifier-11.0.4.pom
[cordova]        file:/Users/pezhvak/Library/Android/sdk/extras/m2repository/com/google/android/gms/play-services-ads-identifier/11.0.4/play-services-ads-identifier-11.0.4.jar
[cordova]        file:/Users/pezhvak/Library/Android/sdk/extras/google/m2repository/com/google/android/gms/play-services-ads-identifier/11.0.4/play-services-ads-identifier-11.0.4.pom
[cordova]        file:/Users/pezhvak/Library/Android/sdk/extras/google/m2repository/com/google/android/gms/play-services-ads-identifier/11.0.4/play-services-ads-identifier-11.0.4.jar
[cordova]        file:/Users/pezhvak/Library/Android/sdk/extras/android/m2repository/com/google/android/gms/play-services-ads-identifier/11.0.4/play-services-ads-identifier-11.0.4.pom
[cordova]        file:/Users/pezhvak/Library/Android/sdk/extras/android/m2repository/com/google/android/gms/play-services-ads-identifier/11.0.4/play-services-ads-identifier-11.0.4.jar
[cordova]        https://maven.google.com/com/google/android/gms/play-services-ads-identifier/11.0.4/play-services-ads-identifier-11.0.4.pom
[cordova]        https://maven.google.com/com/google/android/gms/play-services-ads-identifier/11.0.4/play-services-ads-identifier-11.0.4.jar
[cordova]        https://jcenter.bintray.com/com/google/android/gms/play-services-ads-identifier/11.0.4/play-services-ads-identifier-11.0.4.pom
[cordova]        https://jcenter.bintray.com/com/google/android/gms/play-services-ads-identifier/11.0.4/play-services-ads-identifier-11.0.4.jar
[cordova]        https://dl.google.com/dl/android/maven2/com/google/android/gms/play-services-ads-identifier/11.0.4/play-services-ads-identifier-11.0.4.pom
[cordova]        https://dl.google.com/dl/android/maven2/com/google/android/gms/play-services-ads-identifier/11.0.4/play-services-ads-identifier-11.0.4.jar
[cordova]        https://repo1.maven.org/maven2/com/google/android/gms/play-services-ads-identifier/11.0.4/play-services-ads-identifier-11.0.4.pom
[cordova]        https://repo1.maven.org/maven2/com/google/android/gms/play-services-ads-identifier/11.0.4/play-services-ads-identifier-11.0.4.jar
[cordova]    Required by:
[cordova]        project :app

**Comment by abarisain** [comment]
Closing this as it has been addressed over our customer support a while ago.

For future reference, this kind of problem can be solved by using this plugin: https://github.com/dpa99c/cordova-android-firebase-gradle-release
